.git-clone: &git-clone
  name: git-clone
  git:
    enable: true
    submodules: true

.build-amd64: &build-amd64
  name: build-amd64
  runner:
    tags: cnb:arch:amd64
  services:
    - docker
  env:
    PRIVATE_IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${CNB_COMMIT}-linux-amd64
  stages:
    - name: echo CNB_REPO_NAME
      script: echo ${CNB_REPO_NAME}
    - name: echo Image Name
      script: echo ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}
    - name: docker login
      script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
    - name: docker build Private
      script: docker build -t ${PRIVATE_IMAGE_TAG} .
    - name: docker push Private
      script: docker push ${PRIVATE_IMAGE_TAG}
    - name: resolve
      type: cnb:resolve
      options:
        key: build-amd64

.build-arm: &build-arm
  name: build-arm
  runner:
    tags: cnb:arch:arm64:v8
  services:
    - docker
  env:
    PRIVATE_IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${CNB_COMMIT}-linux-arm64
  stages:
    - name: echo CNB_REPO_NAME
      script: echo ${CNB_REPO_NAME}
    - name: echo Image Name
      script: echo ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}
    - name: docker login
      script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
    - name: docker build Private
      script: docker build -t ${PRIVATE_IMAGE_TAG} .
    - name: docker push Private
      script: docker push ${PRIVATE_IMAGE_TAG}
    - name: resolve
      type: cnb:resolve
      options:
        key: build-arm64
.build-loong64: &build-loong64
  name: build-loong64
  env:
    IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${CNB_COMMIT}-linux-loong64
  docker:
    image: node:22-slim
  runner:
    tags: cnb:arch:amd64:containerd-snapshotter
  services:
    - docker
  stages:
    - name: setting-env
      script:
        - apt-get update -y
        - apt-get install --reinstall ca-certificates -y
    - name: build-web
      script:
        - cd ./admin-webui
        - npm config set registry http://mirrors.tencent.com/npm/ && npm i -g corepack
        - pnpm config set registry https://mirrors.cloud.tencent.com/npm/ && pnpm install && pnpm run build:antd --filter=\!./docs
    # 云原生构建自动构建Docker镜像并将它发布到制品库
    - name: docker login
      script:
        - docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
    - name: docker build && push
      script: |
        docker buildx build --platform linux/loong64 \
          -f Dockerfile.loong64 \
          -t ${IMAGE_TAG} \
          --push .
    - name: resolve
      type: cnb:resolve
      options:
        key: build-loong64
.build-bin: &build-bin
  name: build-bin
  runner:
    tags: cnb:arch:amd64
  services:
    - docker
  docker:
    image: docker.cnb.cool/mliev/open/node-go:node22-pnpm-go1.25.2
  stages:
    - name: build-web
      script:
        - cd ./admin-webui
        - pnpm config set registry https://mirrors.cloud.tencent.com/npm/ && pnpm install && pnpm run build:antd && pnpm run build:oidc && pnpm run build:install
        - cd .. && mkdir -p ./static/admin && cp -a ./admin-webui/apps/web-antd/dist ./static/admin
    - name: changelog
      image: cnbcool/changelog
      exports:
        latestChangeLog: LATEST_CHANGE_LOG
    - name: create release
      type: git:release
      options:
        title: ${CNB_BRANCH}
        description: ${LATEST_CHANGE_LOG}
    - name: go mod
      script: go mod vendor
    - name: go build
      script: goreleaser release --snapshot --clean
    - name: release 上传附件 private
      image: cnbcool/attachments:latest
      settings:
        attachments:
          - ./dist/mliev-push_Darwin_arm64.tar.gz
          - ./dist/mliev-push_Darwin_x86_64.tar.gz
          - ./dist/mliev-push_Linux_arm64.tar.gz
          - ./dist/mliev-push_Linux_armv5.tar.gz
          - ./dist/mliev-push_Linux_armv6.tar.gz
          - ./dist/mliev-push_Linux_armv7.tar.gz
          - ./dist/mliev-push_Linux_loong64.tar.gz
          - ./dist/mliev-push_Linux_x86_64.tar.gz
          - ./dist/checksums.txt
      exports:
        FILES: FILES
    - name: release 上传附件到公开仓库
      image: cnbcool/attachments:latest
      settings:
        attachments:
          - ./dist/mliev-push_Darwin_arm64.tar.gz
          - ./dist/mliev-push_Darwin_x86_64.tar.gz
          - ./dist/mliev-push_Linux_arm64.tar.gz
          - ./dist/mliev-push_Linux_armv5.tar.gz
          - ./dist/mliev-push_Linux_armv6.tar.gz
          - ./dist/mliev-push_Linux_armv7.tar.gz
          - ./dist/mliev-push_Linux_loong64.tar.gz
          - ./dist/mliev-push_Linux_x86_64.tar.gz
          - ./dist/checksums.txt
        # 上传附件到指定仓库
        slug: mliev/open/mliev-push
      exports:
        FILES: FILES
    - name: 输出附件
      script: echo $FILES
    - name: resolve
      type: cnb:resolve
      options:
        key: build-bin
develop:
  push:
    - <<: *git-clone
    #    - <<: *build-loong64
#    - <<: *build-arm
    - <<: *build-amd64

    - services:
        - docker
      name: "push"
      env:
        PRIVATE_IMAGE_NAME: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}
        PUBLIC_IMAGE_NAME: ${CNB_DOCKER_REGISTRY}/mliev/open/mliev-push
      stages:
        - name: await the amd64
          type: cnb:await
          options:
            key: build-amd64
#        - name: await the arm64
#          type: cnb:await
#          options:
#            key: build-arm64
        #        - name: await the loong64
        #          type: cnb:await
        #          options:
        #            key: build-loong64
        - name: manifest private
          image: cnbcool/manifest
          settings:
            target: ${PRIVATE_IMAGE_NAME}:${CNB_BRANCH}
            template: ${PRIVATE_IMAGE_NAME}:${CNB_COMMIT}-OS-ARCH
            platforms:
              - linux/amd64
#              - linux/arm64
        #              - linux/loong64
        - name: manifest public
          image: cnbcool/manifest
          settings:
            target: ${PUBLIC_IMAGE_NAME}:${CNB_BRANCH}
            template: ${PRIVATE_IMAGE_NAME}:${CNB_COMMIT}-OS-ARCH
            platforms:
              - linux/amd64
#              - linux/arm64
        #              - linux/loong64
        - name: remove tag
          type: artifact:remove-tag
          options:
            name: ${CNB_REPO_NAME}
            tags:
              - ${CNB_COMMIT}-linux-amd64
#              - ${CNB_COMMIT}-linux-arm64
            #              - ${CNB_COMMIT}-linux-loong64
            type: docker

$:
  tag_push:
    - <<: *git-clone
    - <<: *build-amd64
    - <<: *build-arm
    #    - <<: *build-loong64
    #    - <<: *build-bin
    - services:
        - docker
      name: "push"
      env:
        PRIVATE_IMAGE_NAME: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}
        PUBLIC_IMAGE_NAME: ${CNB_DOCKER_REGISTRY}/mliev/open/mliev-push
      stages:
        - name: await the amd64
          type: cnb:await
          options:
            key: build-amd64
        - name: await the arm64
          type: cnb:await
          options:
            key: build-arm64
        #        - name: await the loong64
        #          type: cnb:await
        #          options:
        #            key: build-loong64
        #        - name: await the build-bin
        #          type: cnb:await
        #          options:
        #            key: build-bin
        - name: manifest latest private
          image: cnbcool/manifest
          settings:
            target: ${PRIVATE_IMAGE_NAME}:latest
            template: ${PRIVATE_IMAGE_NAME}:${CNB_COMMIT}-OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64
        #              - linux/loong64
        - name: manifest version private
          image: cnbcool/manifest
          settings:
            target: ${PRIVATE_IMAGE_NAME}:${CNB_BRANCH}
            template: ${PRIVATE_IMAGE_NAME}:${CNB_COMMIT}-OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64
        #              - linux/loong64
        - name: manifest latest public
          image: cnbcool/manifest
          settings:
            target: ${PUBLIC_IMAGE_NAME}:latest
            template: ${PRIVATE_IMAGE_NAME}:${CNB_COMMIT}-OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64
        #              - linux/loong64
        - name: manifest version public
          image: cnbcool/manifest
          settings:
            target: ${PUBLIC_IMAGE_NAME}:${CNB_BRANCH}
            template: ${PRIVATE_IMAGE_NAME}:${CNB_COMMIT}-OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64
        #              - linux/loong64
        - name: remove tag
          type: artifact:remove-tag
          options:
            name: ${CNB_REPO_NAME}
            tags:
              - ${CNB_COMMIT}-linux-amd64
              - ${CNB_COMMIT}-linux-arm64
            #              - ${CNB_COMMIT}-linux-loong64
            type: docker
